# Configurações de conexão com banco de dados
# Este arquivo é usado localmente para desenvolvimento

[secrets]
DB_HOST = "10.64.1.11"
DB_PORT = "50000"
DB_NAME = "SAB"
DB_USER = "db2user_ro"
DB_PASSWORD = "Sup3rs44nt0"

# Configurações adicionais
DB_DRIVER = "IBM DB2 ODBC DRIVER"
DB_PROTOCOL = "TCPIP"
